name: Docker CI

on:
  push:
    tags:
      - '[0-9]+.[0-9]+'
    branches: [staging, production]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: docker/login-action@3
      name: Log in to Docker Hub
      with:
        username: ${{ vars.DOCKER_ACCOUNT }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - uses: docker/metadata-action@5
      name: Docker metadata
      with:
        image: ${{ vars.DOCKER_ACCOUNT}}/${{ vars.DOCKER_REPOSITORY }}
        tags: |
            type=sha
            type=ref,event=tag

    - uses: docker/build-push-action@6
      name: Build and push
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
